config/routes.rb
Network::Application.routes.draw do
  get "profiles/show"
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new' 
    get 'signin', to: 'devise/sessions#new' 
  end

  resources :relationships, only: [:create, :destroy]

  get "landing_page/index"
  resources :events do
    resources :comments
  end
  root 'landing_page#index'
  get '/:id', to: 'profiles#show'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user

  #FOR SOME REASON the below won't say anything, but do disallow user as needed :/
  validates :user_id, presence: true
  validates :body, presence: true,
  								 length: { minimum: 2 }
end

app/models/event.rb
 class Event < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user #added after seeing in treehouse version; works without on localhost 3/7

	validates :title, presence: true,
                    length: { minimum: 5 }
  validates :text, presence: true,
  								 length: { minimum: 2 }
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User", foreign_key: 'followed_id'
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :interests
  #groups
  has_many :events #added after seeing in treehouse; 3/7 works fine localhost w/o
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                             with: /\A[a-zA-Z0-9_-]+\Z/,
                             message: 'Must be formatted correctly.'
                           }


  def full_name
  	first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
#added destroy, not in Treebook 

	def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create(params[:comment].permit( :body, :user, :user_id, :first_name, :profile_name))
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
    @comment.destroy
    redirect_to event_path(@event)
  end
end

#each request for a comment has to keep track of the post to which the comment is attached, thus the initial call to the find method of the Post model to get the post in question.


#The destroy action will find the post we are looking at, locate the comment within the @post.comments collection, and then remove it from the database and send us back to the show action for the post.

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
	#added destroy to above, not in Treebook

	def index
		@events = Event.all 
	end
	
	def new # diff between new and create?
		@event = Event.new
	end

	def create #save our new event to a database
		@event = Event.new(params[:event].permit(:title, :text, :event_start))
		#@event = current_user.events.new(params[:events])

		#respond_to do|format|

		if @event.save
			redirect_to @event 
		else
			render 'new'
			#The render method is used so that the @post 
			#object is passed back to the new template when it is rendered. 
			#This rendering is done within the same request as the form 
			#submission, whereas the redirect_to will tell the browser to issue another request.
		end
	end
	#end #for respond_to; noticed in "What is a join table"

	def show #show, being an action
		@event = Event.find(params[:id])
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		#first line begins below =================
		#@event = current_user.events.find(params[:id])
		#if params[:event && params[:status].has_key?(:user_id)
		#params[:event].delete(:user_id)
		#end
		#respond_to do |format|

		if @event.update(event_params)
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy
		@event = Event.find(params[:id])

		@event.destroy

		redirect_to events_path
	end

#def status_params
#    params.require(:status).permit(:name, :content, :user_id)
#    end
    
	private
		def event_params
			params.require(:event).permit(:title, :text, :user_id, :event_start)
		end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def show
    @user = User.find_by_profile_name(params[:id])
    if @user
			@events = Event.all 
			#@events = @user.events.all
			#gets undefined method 'events' for #<User:0x5760630>    
      render action: :show
    else
      render file: 'public/404', event: 404, formats: [:html]
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	#before_filter :authentication_user!, only:[:new]
	before_action :signed_in_user

  #def create
  #  @user = User.find(params[:relationship][:followed_id])
  #  current_user.follow!(@user)
  #  redirect_to @user
  #end

  #def destroy
  #  @user = Relationship.find(params[:id]).followed
  #  current_user.unfollow!(@user)
  #  redirect_to @user
  #end
#end

	def new
		if params[:followed_id]
			@followed = User.find(params[:followed_id])
			@relationship = current_user.user_relationships.new(friend: @friend)
		else
			flash[:error] = "Requires someone someone to follow"
		end
	rescue ActiveRecord::RecordNotFound
  	render file: 'public/404', status: :not_found
  end 
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def sign_up_params
     params.require(:user).permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when :alert
			"alert-warning"

		when :notice
			"alert-warning"
		else ""
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
<p>
  <strong><%= link_to comment.user.full_name, profiles_show_path %></strong> 
</p>

<p>  
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.event, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
</div>



app/views/comments/_form.html.erb
<%= simple_form_for([@event, @event.comments.build]) do |f| %>

  <p>
    <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render 'form' %>
 
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="page-header">
  <h1>All Events</h1>
</div>

<%= link_to 'New event', new_event_path, class: "btn btn-primary" %>
<div id="post-btn-margin">
</div>
<% @events.each do |event| %>
<div class="event">
  <span id="event-index-title"><h3><%= link_to event.title, event %></h3></span>
  <p>
  <%= event.text %>
  </p>
  <div class="meta">
    
    <span id="gray-time">
    <%= time_ago_in_words(event.created_at) + " ago" %>
    </span>
    <span class ="admin">
      | <%= link_to "Edit", edit_event_path(event) %> |
      <%= link_to "Delete", event, method: :delete, data: { confirm: "Are you sure?"} %>
    </span>
  </div>
</div>
<% end %>








app/views/events/new.html.erb
<h1>Post a New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<hr/>
<div class="event-present">
	<div id="event-title">
		<h1>
		  <p>
			  <%= @event.title %></span>
			</p>
		</h1>
	</div>

	<p>
		<h3><%= @event.event_start.strftime("%B %e, %Y") %></h3>
	</p>
	
	<p>
	  <%= @event.text %>
	</p>

</div>
<hr/>

<h3>Comments</h3>

<p>
	<%= render @event.comments %></p>
</p>

<h4>Add a comment:</h4>
<%= render "comments/form" %>

<%= link_to 'Edit event', edit_event_path(@event) %> |
<%= link_to 'Back to events', events_path %>



app/views/landing_page/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Static Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="app/assets/stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="app/assets/stylesheets/navbar-static-top.css" rel="stylesheet">
    <link href="app/assets/stylesheets/my-styles.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
  </head>

  <div id="margin-top">
  </div>

  <body>

    <div class="container">
      <div class="row jumbotron">
        <!-- Main component for a primary marketing message or call to action -->
        
          <div class="col-sm-7">
            <h1>Navbar example</h1>
            <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
            <p>To see the difference between static and fixed top navbars, just scroll.</p>
            <p>
              <a class="btn btn-lg btn-primary" href="bootstrap/components/#navbar" role="button">View navbar docs &raquo;</a>
            </p>
          </div>

          <div class="col-sm-1">
          </div>

          
            <form class="form-signin col-sm-4 well" role="form">
              <h2 class="form-signin-heading">Sign Up</h2><hr>

              <form class="form-inline" role="form">

                <div class="form-group">
                  <label class="sr-only" for="#">First name</label>
                  <input type="text" class="form-control" id="#" placeholder="First name">
                </div>

                <div class="form-group">
                  <label class="sr-only" for="#">Last name</label>
                  <input type="text" class="form-control" id="#" placeholder="Last name">
                </div>
                
                <div class="form-group">
                  <input type="email" class="form-control" placeholder="Email address" required autofocus>
                </div>

                <div class="form-group">
                  <input type="email" class="form-control" placeholder="Type email again" required autofocus>
                </div>

                <div class="form-group">
                  <input type="password" class="form-control" placeholder="Password" required>
                </div>

               <div class="form-group">
                  <div class="">
                    <div class="checkbox">
                      <label>
                        <input type="checkbox"> Remember me
                      </label>
                    </div>
                  </div>
                </div>

              <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
            </form>
          
          
        </div>
      
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Network</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<!-- Static navbar -->
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Project name</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!--<li class="active"><a href="#">Home</a></li>-->
          <li><%= link_to 'All events', events_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <!--<li><a href="../navbar/">Default</a></li>
          <li class="active"><a href="./">Static top</a></li>-->
          
          <% if user_signed_in? %>
            
            <li><%= link_to current_user.full_name, edit_user_registration_path %></li><li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li><!-- THIS CHANGES THE METHOD FROM 'GET' TO DELETE, SO WE DON'T GET AN ERROR-->
          <% else %>
            <form class="navbar-form navbar-right" role="form">
              <div class="form-group">
                <input type="email" placeholder="Enter email" class="form-control">
              </div>
              <div class="form-group">
                <input type="password" placeholder="Password" class="form-control">
              </div>
              <!-- Maybe a dropdown later, with clearly visible invert traingle <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember me
                </label>
              </div>-->
              <button type="submit" class="btn btn-default">Sign in</button>

            </form>
            <li><%= link_to "Sign Up", signup_path %></li>
          <% end %>

        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="container">
    <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>">
        <button class="close" data-dismiss="alert">x</button>
        <%= message %>
      </div>
    <% end %>
    
		<%= yield %>
	</div>

</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>

<% if @events %>
	<% @events.each do |event| %>
		<div class="profile">
			<%= event.text %>
			
			<%= link_to time_ago_in_words(event.created_at) + " ago", event_path(event) %> 
		</div>
	<% end %>
<% end %>

app/views/relationships/new.html.erb
<!--<% if @followed_id %>
	<h1><%= @followed_id.full_name %></h1>
<% end %>

<%= form_for @user_friendship, method: :post do |form| %>
	<div class="form form-actions">-->

<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if signed_in? %>